# Conexão com o Banco
spring.datasource.url=jdbc:postgresql://localhost:5433/sivec
spring.datasource.username=postgres
spring.datasource.password=132419
spring.datasource.driver-class-name=org.postgresql.Driver

# Forçar o Hibernate a criar as tabelas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração do Token (Para não dar erro no boot)
api.security.token.secret=${JWT_SECRET:12345678}
